require_relative 'bishop'
require_relative 'rook'
require_relative 'king'
require_relative 'queen'
require_relative 'knight'
require_relative 'pawn'
require_relative 'null_piece'
require_relative 'piece'
